[package]
name = "meetnote2"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "system-tray", "window-create", "window-close", "notification-all", "shell-open"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"

dirs = "5.0.1"
dirs-sys = "0.4.1"

walkdir = "2.4.0"

log = { version = "0.4.20", features = [] }
simplelog = "0.12.1"

anyhow = { version = "1.0.75", features = [] }

reqwest = { version = "0.11.22", features = ["blocking", "multipart", "json"] }

chrono = { version = "0.4.31", features = [] }

# sound
cpal = "0.15.2"
hound = "3.5.1"

glob = "0.3.1"

# screencapturekit
core-graphics = "0.23.1"
screencapturekit = "0.2.2"
config = "0.13.4"
time = "0.3.30"
tempfile = { version = "3.9.0", features = [] }
uuid = { version = "1.6.1", features = ["v4"] }
regex = "1.10.2"
base64 = "0.21.7"

lindera-tokenizer = { version = "0.27.1", features = ["ipadic"] }
lindera-analyzer = { version = "0.27.1", features = ["ipadic", "ipadic-filter"] }
lindera-dictionary = "0.27.1"
lindera-core = "0.27.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
